---
title: "Análisis de datos"
author: "Chuquizuta Poquioma Shirley,  García López Llian Carlos,  Montoya Vargas Oscar Enrique,  Tuesta Melendez Lleily Consuelo"
format: html
editor_options: 
  chunk_output_type: console
---
s
# Diseñar el experimento

$$alt_plant = \mu + producto + dosis+ producto*dosis + bloq + e$$

# Cargar los paquetes
```{r}
library(tidyverse)
library(googlesheets4)
library(emmeans)
library(multcomp)
library(multcompView)
library(knitr)
```
# Importar los datos
```{r}
url <- "https://docs.google.com/spreadsheets/d/1FsG1M0WFQ8531TRAjBTDFO4uZdZJNI51VYCHsvlx0Jg/edit?gid=1217457001#gid=1217457001"

gs <- url %>% 
  as_sheets_id()

fb <- gs %>% 
  range_read("fb") %>% 
    mutate(across(1:dosis, ~as.factor(.)))
str(fb)
```

# Análisis para alt_plant

## ANOVA
```{r}
md <- aov(alt_plant ~ bloq + producto*dosis, data = fb)

anova(md)
```

## Comparación de medias
```{r}
emm_int <- emmeans(md, ~ producto * dosis)
cld_int <- cld(
  emm_int,
  adjust = "tukey",
  Letters = letters,
  alpha = 0.05
) %>% 
  as_tibble() %>% 
  mutate(
    .group = stringr::str_trim(.group)
  )

cld_int %>% kable()
```

## Gráfico
```{r}
ggplot(cld_int, aes(x = producto, y = emmean, fill = dosis)) +
  geom_col(position = position_dodge(width = 0.8)) +
  geom_errorbar(
    aes(ymin = lower.CL, ymax = upper.CL),
    position = position_dodge(width = 0.8),
    width = 0.2
  ) +
  geom_text(
    aes(label = .group, y = upper.CL),
    position = position_dodge(width = 0.8),
    vjust = -0.4,
    size = 4
  ) +
  labs(
    x = "Producto biológico",
    y = "alt_plant (media marginal ± IC95%)",
    fill = "Dosis",
    title = "Comparación de medias de altura de planta según producto y dosis"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
```

# Análisis para long_raiz

## ANOVA
```{r}
md <- aov(long_raiz ~ bloq + producto*dosis, data = fb)

anova(md)
```

## Comparación de medias
```{r}
emm_int <- emmeans(md, ~ producto * dosis)
cld_int <- cld(
  emm_int,
  adjust = "tukey",
  Letters = letters,
  alpha = 0.05
) %>% 
  as_tibble() %>% 
  mutate(
    .group = stringr::str_trim(.group)
  )
```

## Gráfico
```{r}
ggplot(cld_int, aes(x = producto, y = emmean, fill = dosis)) +
  geom_col(position = position_dodge(width = 0.8)) +
  geom_errorbar(
    aes(ymin = lower.CL, ymax = upper.CL),
    position = position_dodge(width = 0.8),
    width = 0.2
  ) +
  geom_text(
    aes(label = .group, y = upper.CL),
    position = position_dodge(width = 0.8),
    vjust = -0.4,
    size = 4
  ) +
  labs(
    x = "Producto biológico",
    y = "long_raiz (media marginal ± IC95%)",
    fill = "Dosis",
    title = "Comparación de medias de longitud de raiz según producto y dosis"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
```

# Análisis para num_nudos

## ANOVA
```{r}
md <- aov(num_nudos ~ bloq + producto*dosis, data = fb)

anova(md)
```

## Comparación de medias
```{r}
emm_int <- emmeans(md, ~ producto * dosis)
cld_int <- cld(
  emm_int,
  adjust = "tukey",
  Letters = letters,
  alpha = 0.05
) %>% 
  as_tibble() %>% 
  mutate(
    .group = stringr::str_trim(.group)
  )
```

## Gráfico
```{r}
ggplot(cld_int, aes(x = producto, y = emmean, fill = dosis)) +
  geom_col(position = position_dodge(width = 0.8)) +
  geom_errorbar(
    aes(ymin = lower.CL, ymax = upper.CL),
    position = position_dodge(width = 0.8),
    width = 0.2
  ) +
  geom_text(
    aes(label = .group, y = upper.CL),
    position = position_dodge(width = 0.8),
    vjust = -0.4,
    size = 4
  ) +
  labs(
    x = "Producto biológico",
    y = "long_raiz (media marginal ± IC95%)",
    fill = "Dosis",
    title = "Comparación de medias de longitud de raiz según producto y dosis"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
```
